In [1]:
# Importing libraries
import numpy as np
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
# Load the data... we skip the date format (column 1) because it doesn't work. 
# Wen Jun, do you have any idea to work it?
X = np.loadtxt('Data/train.csv',  delimiter=',', skiprows=1, usecols=range(2, 14))
y = np.loadtxt('Data/train.csv', delimiter=',', skiprows=1, usecols=[14])

test_X = np.loadtxt('Data/test.csv', delimiter=',', skiprows=1, usecols=range(2, 14))

In [3]:
# Creating linear models for training
from sklearn.cross_validation import KFold
kf = KFold(n=len(X),n_folds = 10)
for tr, te in kf:
    print(tr, te)

(array([ 1089,  1090,  1091, ..., 10883, 10884, 10885]), array([   0,    1,    2, ..., 1086, 1087, 1088]))
(array([    0,     1,     2, ..., 10883, 10884, 10885]), array([1089, 1090, 1091, ..., 2175, 2176, 2177]))
(array([    0,     1,     2, ..., 10883, 10884, 10885]), array([2178, 2179, 2180, ..., 3264, 3265, 3266]))
(array([    0,     1,     2, ..., 10883, 10884, 10885]), array([3267, 3268, 3269, ..., 4353, 4354, 4355]))
(array([    0,     1,     2, ..., 10883, 10884, 10885]), array([4356, 4357, 4358, ..., 5442, 5443, 5444]))
(array([    0,     1,     2, ..., 10883, 10884, 10885]), array([5445, 5446, 5447, ..., 6531, 6532, 6533]))
(array([    0,     1,     2, ..., 10883, 10884, 10885]), array([6534, 6535, 6536, ..., 7619, 7620, 7621]))
(array([    0,     1,     2, ..., 10883, 10884, 10885]), array([7622, 7623, 7624, ..., 8707, 8708, 8709]))
(array([    0,     1,     2, ..., 10883, 10884, 10885]), array([8710, 8711, 8712, ..., 9795, 9796, 9797]))
(array([   0,    1,    2, ..., 9795, 

In [4]:
from sklearn.neighbors import KNeighborsRegressor

In [5]:
neigh = KNeighborsRegressor(n_neighbors=5)
neigh.fit(X, y)
res = np.rint(np.absolute(neigh.predict(test_X)))
np.savetxt('knn.csv', res, delimiter=',')

[  10.    5.    3. ...,  174.  122.   75.]
